version: '3.8'

services:
  backend:
    image: lebenchallenge-backend
    build:
      context: ./LebenChallenge
      dockerfile: dockerfile
    ports:
      - "5000:80"
    
  frontend:
    image: lebenchallenge-frontend
    build:
      context: ./lebenchallengefront
      dockerfile: dockerfile
    ports:
      - "3000:80"