# Etapa de construcción
FROM node:18 AS build
WORKDIR /app

# Copiar archivos de dependencias y restaurarlas
COPY package*.json ./
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Etapa de ejecución
FROM nginx:alpine AS runtime

# Copiar los archivos compilados al directorio de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer el puerto 80 para el servidor Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]